global:
  backendName: sausage-backend
  backendPort: 8080

backend:
  name: sausage-backend
  revisionHistoryLimit: 12
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  image: gitlab.praktikum-services.ru:5050/std-000-00/sausage-store/sausage-backend:1.0.2400417
  containerPort: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m" 
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
  vpa:
    updateMode: "Off"
    resources:
      minAllowed:
        cpu: 250m
        memory: 64Mi
      maxAllowed:
        cpu: 1
        memory: 500Mi
      
backend-report:
  name: sausage-backend-report
  revisionHistoryLimit: 12
  strategy: Recreate
  image:  gitlab.praktikum-services.ru:5050/std-000-00/sausage-store/sausage-backend-report:1.0.2346847
  hpa:
    resources:
      minReplicas: 2
      maxReplicas: 5
      averageUtilization: 75
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6

frontend:
  name: sausage-store-frontend
  fqdn: "ivanov-ivan-000.k8s.praktikum-services.tech"
  revisionHistoryLimit: 12
  port: 80
  replicas: 1
  strategy: Recreate
  image:  gitlab.praktikum-services.ru:5050/std-000-00/sausage-store/sausage-frontend:1.0.2346845
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m" 
