# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret-frontend
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6eyJ1c2VybmFtZSI6InNhdXNhZ2Utc3RvcmUiLCJwYXNzd29yZCI6IlVzemk4SDVQb0xDUXBiM1QzeHl3IiwiYXV0aCI6ImMyRjFjMkZuWlMxemRHOXlaVHBWYzNwcE9FZzFVRzlNUTFGd1lqTlVNM2g1ZHc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
