---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.port | int }}
      targetPort: {{ .Values.port | int }}
  selector:
    app: "{{ .Values.name }}"
