---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
data:
  nginx.conf: |
    server {

      listen {{ .Values.port }};

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }

      location ~ ^/(categories|products|auth|metrics|orders)/ {
        proxy_pass http://{{ .Values.global.backendName }}:{{ .Values.global.backendPort | int }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
