# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret-backend-report
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6eyJ1c2VybmFtZSI6InNhdXNhZ2Utc3RvcmUiLCJwYXNzd29yZCI6IlVzemk4SDVQb0xDUXBiM1QzeHl3IiwiYXV0aCI6ImMyRjFjMkZuWlMxemRHOXlaVHBWYzNwcE9FZzFVRzlNUTFGd1lqTlVNM2g1ZHc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson

# Секрет, необходимый, чтобы соединяться с MongoDB
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: mongo
data:
  mongo_url: >-
    bW9uZ29kYjovL3N0ZC0wNDEtMzQ6VGVzdHVzcjEyMzRAcmMxZC04ams0c3JhcXJ1OGplcmtnLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTA0MS0zND90bHM9dHJ1ZSZ0bHNDYUZpbGU9L2FwcC9ZYW5kZXhJbnRlcm5hbFJvb3RDQS5jcnQ=
type: Opaque
