include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}/momo-store-frontend:$CI_COMMIT_SHA"

stages:
  - pre-build
  - build
  - test
  - release
  - deploy

secret_detection:
  stage: pre-build
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "false"
    GIT_STRATEGY: "clone"
  allow_failure: true
  script:
    - apk add jq
    - /analyzer run
    - exit $(eval "cat gl-secret-detection-report.json | jq --raw-output '.vulnerabilities | length'")
  artifacts:
    when: always
    paths:
      - gl-secret-detection-report.json

sast:
  stage: pre-build
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, gosec, eslint, nodejs-scan
  artifacts:
    paths:
      - ${CI_JOB_NAME}.json
  after_script:
    - mv gl-sast-report.json ${CI_JOB_NAME}.json

trivy-sca:
  stage: pre-build
  allow_failure: true
  image:
    name: aquasec/trivy:0.57.0
    entrypoint: [""]
  script:
    - trivy fs -f json --output trivy-sca.json .
  artifacts:
    paths:
      - trivy-sca.json
  rules:
    - if: $CI_COMMIT_BRANCH

build-frontend-image-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true 

container_scanning:
  variables:
    GIT_STRATEGY: "clone"
    CS_DOCKERFILE_PATH: "./frontend/Dockerfile"
    CS_IMAGE: "${CI_REGISTRY_IMAGE}/momo-store-frontend:$CI_COMMIT_SHA"
  needs: 
  - build-frontend-image-job

release-frontend-image:
  stage: release
  needs:
    - build-frontend-image-job
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/momo-store-frontend:$CI_COMMIT_SHA $VERSION
    - crane tag $CI_REGISTRY_IMAGE/momo-store-frontend:$CI_COMMIT_SHA latest