variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines

    
frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*
      
backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

infrastructure:
  stage: module-pipelines
  trigger:
    include:
      - "/infrastructure/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infrastructure/**/*