apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      receiver: "telegram"

    receivers:
    - name: "telegram"
      telegram_configs:
      - send_resolved: true
        api_url: '{{ .Values.telegram_api_url }}'
        bot_token: '{{ .Values.telegram_bot_token }}'
        chat_id: {{ .Values.telegram_chat_id }}
        message: "Alert: {{ "{{ .CommonLabels.alertname }}" }}\nStatus: {{ "{{ .Status }}" }}\nSeverity: {{ "{{ .CommonLabels.severity }}" }}\nInstance: {{ "{{ .CommonLabels.instance }}" }}\nSummary: {{ "{{ .CommonAnnotations.summary }}" }}"