apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.app_fqdn }}
    - prom.{{ .Values.app_fqdn }}
    - grafana.{{ .Values.app_fqdn }}  
    secretName: tls-secret-app
  rules:
    - host: {{ .Values.app_fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.frontendName }}
                port:
                  number: {{ .Values.global.frontendPort }}
    - host: prom.{{ .Values.app_fqdn }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.prometheusName }}
                port:
                  number: {{ .Values.global.prometheusPort }}
    - host: grafana.{{ .Values.app_fqdn }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.grafanaName }}
                port:
                  number: {{ .Values.global.grafanaPort }}
