# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: YUhSMGNEb3ZMM04wWkMwd05ERXRNelF1Y0hKaGEzUnBhM1Z0TFhObGNuWnBZMlZ6TG5SbFkyZzZPREl3TUE9PQ==
  vault_host: aHR0cDovL3N0ZC0wNDEtMzQucHJha3Rpa3VtLXNlcnZpY2VzLnRlY2g6ODIwMA==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6eyJ1c2VybmFtZSI6InNhdXNhZ2Utc3RvcmUiLCJwYXNzd29yZCI6IlVzemk4SDVQb0xDUXBiM1QzeHl3IiwiYXV0aCI6ImMyRjFjMkZuWlMxemRHOXlaVHBWYzNwcE9FZzFVRzlNUTFGd1lqTlVNM2g1ZHc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson

# Секрет, необходимый, чтобы соединяться с PostgresSQL
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
data:
  psql_user: c3RkLTA0MS0zNA==
  psql_password: VGVzdHVzcjEyMzQ=
  psql_url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxZC1hMTk0OGxpNm12aGp0aXFtLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDQxLTM0P3NzbD10cnVlJnNzbHJvb3RjZXJ0PS9hcHAvWWFuZGV4SW50ZXJuYWxSb290Q0EuY3J0
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: address
  labels:
    app: address
data:
  LOG_FILE: c2F1c2FnZS1zdG9yZS1iYWNrZW5kLmxvZw==
  LOG_PATH: L3RtcC9zYXVzYWdlLXN0b3JlL2xvZ3M=
  REPORT_PATH: L3RtcC9zYXVzYWdlLXN0b3JlL3JlcG9ydHM=
  mongo_url: bW9uZ29kYjovL3N0ZC0wNDEtMzQ6VGVzdHVzcjEyMzRAcmMxZC04ams0c3JhcXJ1OGplcmtnLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTA0MS0zND90bHM9dHJ1ZQ==
type: Opaque