# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: YUhSMGNEb3ZMM04wWkMwd05ERXRNelF1Y0hKaGEzUnBhM1Z0TFhObGNuWnBZMlZ6TG5SbFkyZzZPREl3TUE9PQ==
  vault_host: aHR0cDovL3N0ZC0wNDEtMzQucHJha3Rpa3VtLXNlcnZpY2VzLnRlY2g6ODIwMA==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6eyJ1c2VybmFtZSI6InNhdXNhZ2Utc3RvcmUiLCJwYXNzd29yZCI6IlVzemk4SDVQb0xDUXBiM1QzeHl3IiwiYXV0aCI6ImMyRjFjMkZuWlMxemRHOXlaVHBWYzNwcE9FZzFVRzlNUTFGd1lqTlVNM2g1ZHc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson

# Секрет, необходимый, чтобы соединяться с MongoDB
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: mongo
data:
  mongo_url: >-
    bW9uZ29kYjovL3N0ZC0wNDEtMzQ6VGVzdHVzcjEyMzRAcmMxZC04ams0c3JhcXJ1OGplcmtnLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTA0MS0zND90bHM9dHJ1ZSZ0bHNDYUZpbGU9L2FwcC9ZYW5kZXhJbnRlcm5hbFJvb3RDQS5jcnQ=
type: Opaque
