---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
data:
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "rules/" $key }}
  {{ $key | trimPrefix "rules/" }}: {{ $files.Get $key | quote }}
  {{- end }}
  {{- end }}