apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-serviceaccount
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.name }}"
    app.kubernetes.io/name: momo-prometheus
    app.kubernetes.io/instance: "{{ .Release.Name }}"