apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.prometheusName }}"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.global.prometheusPort }}
      protocol: TCP
      targetPort: {{ .Values.global.prometheusPort }}
  selector:
    app: "{{ .Values.name }}"