apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-admin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  admin-user: {{ .Values.adminUser | b64enc | quote }}