---
apiVersion: v2
type: application
name: momo-store
description: Momo Store Helm Chart

version: 0.1.7
appVersion: "latest"

dependencies:
  - name: backend
    version: 0.1.7
  - name: frontend
    version: 0.1.8
  - name: ingress
    version: 0.1.4
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
  - name: prometheus
    version: 0.0.1
  - name: grafana
    version: 0.17.0